#!/usr/bin/env python

import sys


def read_file():
    file = open(sys.argv[1], "r")
    file_data = file.readlines()

    hex_key = list(file_data[0])
    hex_string = list(file_data[1])


    hex_key_to_list = []

    hex_key.remove('\n')
    hex_string.remove('\n')

    n = 0
    while True:
        for i in range(0, len(hex_key)):
            if len(hex_key_to_list) == len(hex_string):
                break
            hex_key_to_list.append(hex_key[i])
            n += 1

        if len(hex_key_to_list) < len(hex_string):
            continue
        else:
            break


    hex_key_list_to_string = ''.join(hex_key_to_list)
    key_list_to_string = ''.join(hex_string)

    binary_hex_key_string = hex_key_list_to_string.decode("hex")
    binary_hex_string = key_list_to_string.decode("hex")

    xored = xor_strings(binary_hex_key_string, binary_hex_string).encode("hex")
    print(xored.upper())


def xor_strings(xs, ys):
    return "".join(chr(ord(x) ^ ord(y)) for x, y in zip(xs, ys))


if len(sys.argv) != 2:
    sys.exit(84)

read_file()
sys.exit(0)