#!/usr/bin/env python

import sys

def read_file():
    file_open = open(sys.argv[1], "r")
    file_data = file_open.readlines()
    data = []
    for fdata in range(0, len(file_data)):
        for n in range(0, len(file_data[fdata]) - 1):
            if file_data[fdata][n] == " ":
                continue
            data.append(file_data[fdata][n])

        data_hex = []
        for i in range(0, len(data) - 1):
            hex = data[i] + data[i + 1]
            if i % 2 == 0:
                data_hex.append(hex)
        return data_hex

def convert_to_baser64(hexa):
    base64 = hexa.decode("hex").encode("base64")
    sys.stdout.write(base64)


if len(sys.argv) != 2:
    sys.exit(84)

hex = read_file()
for nbHexa in range(0, len(hex)):
    convert_to_baser64(hex[nbHexa])
sys.exit(0)