#!/usr/bin/env python

import sys

def read_file():
    file_open = open(sys.argv[1], "r")
    file_data = file_open.readlines()
    if len(file_data[0]) != len(file_data[1]):
        sys.exit(84)

    data_only_hex1 = ""
    data_only_hex2 = ""
    for n in range(0, len(file_data[0]) - 1):
        data_only_hex1 += file_data[0][n]
        data_only_hex2 += file_data[1][n]

    binary_a = data_only_hex1.decode("hex")
    binary_b = data_only_hex2.decode("hex")

    xored = xor_strings(binary_a, binary_b).encode("hex")
    print(xored.upper())

def xor_strings(xs, ys):
    return "".join(chr(ord(x) ^ ord(y)) for x, y in zip(xs, ys))

if __name__ == '__main__':
	if len(sys.argv) != 2:
		sys.exit(84)

	read_file()
	sys.exit(0)